# Generated by Django 4.1.2 on 2022-10-06 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of updates')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of updates')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='Summary')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of updates')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issue', to='webapp.status', verbose_name='Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issue', to='webapp.type', verbose_name='Type')),
            ],
        ),
    ]
